use_frameworks!

platform :ios, '13.0'
use_frameworks! :linkage => :static
install! 'cocoapods', :deterministic_uuids => false
install! 'cocoapods', :disable_input_output_paths => true

target 'STFlightKit_Example' do
  pod 'STFlightKit', :path => '../'
  pod 'STCoreKit', :git => 'https://github.com/abmomen/STCoreKit.git'

  target 'STFlightKit_Tests' do
    inherit! :search_paths

    
  end
end
