use_frameworks!

platform :ios, '13.0'

target 'STFlightKit_Example' do
  pod 'STFlightKit', :path => '../'
  pod 'STCoreKit', :git => 'https://github.com/abmomen/STCoreKit.git'

  target 'STFlightKit_Tests' do
    inherit! :search_paths

    
  end
end
